import fs from "node:fs/promises";
import path from "node:path";
import { loadBlogSources, type BlogSource } from "./blog-content";

function assertManagedOutput(publicBlogRoot: string, slug: string) {
  const output = path.resolve(publicBlogRoot, slug);
  const relative = path.relative(publicBlogRoot, output);
  if (relative.startsWith("..") || path.isAbsolute(relative)) {
    throw new Error(`Refusing to manage an asset directory outside ${publicBlogRoot}.`);
  }
  return output;
}

function toPublicPost(source: BlogSource) {
  const imageRoot = `/images/blog/scheduled/${source.slug}`;
  return {
    slug: source.slug,
    title: source.title,
    date: source.publishAt.slice(0, 10),
    publishAt: source.publishAt,
    category: source.category,
    excerpt: source.excerpt,
    featuredImage: `${imageRoot}/${path.basename(source.featuredImage)}`,
    featuredImageAlt: source.featuredImageAlt,
    inlineImages: (source.inlineImages ?? []).map((image) => ({
      after: image.after,
      src: `${imageRoot}/${path.basename(image.source)}`,
      alt: image.alt,
      caption: image.caption,
    })),
    content: source.content,
  };
}

async function copyPostAssets(
  publicBlogRoot: string,
  postDirectory: string,
  source: BlogSource,
) {
  const outputDirectory = assertManagedOutput(publicBlogRoot, source.slug);
  await fs.mkdir(outputDirectory, { recursive: true });

  const assets = [
    source.featuredImage,
    ...(source.inlineImages ?? []).map((image) => image.source),
  ];
  for (const asset of assets) {
    await fs.copyFile(path.resolve(postDirectory, asset), path.join(outputDirectory, path.basename(asset)));
  }
}

async function main() {
  const repositoryRoot = process.cwd();
  const sources = await loadBlogSources(repositoryRoot);
  const publicBlogRoot = path.resolve(repositoryRoot, "client", "public", "images", "blog", "scheduled");
  const generatedSource = path.resolve(
    repositoryRoot,
    "client",
    "src",
    "generated",
    "blogs.ts",
  );

  await fs.mkdir(publicBlogRoot, { recursive: true });
  for (const { source } of sources) {
    const outputDirectory = assertManagedOutput(publicBlogRoot, source.slug);
    await fs.rm(outputDirectory, { recursive: true, force: true });
  }

  for (const post of sources) {
    await copyPostAssets(publicBlogRoot, post.directory, post.source);
  }

  const generatedPosts = sources.map(({ source }) => toPublicPost(source));
  const generatedCode = [
    "/* This file is generated by scripts/generate-blog-content.ts. */",
    'import type { BlogPost } from "../lib/blogs";',
    "",
    `export const GENERATED_BLOG_POSTS: BlogPost[] = ${JSON.stringify(generatedPosts, null, 2)};`,
    "",
  ].join("\n");

  await fs.mkdir(path.dirname(generatedSource), { recursive: true });
  await fs.writeFile(generatedSource, generatedCode, "utf8");

  console.log(`Prepared ${sources.length} blog post(s) for timestamp-based browser publication.`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
